### ISSUE TITLE
Turtle forward methods should support `track_angle` argument

### ISSUE THREAD

**Issue by tmontes** [tmontes/python-aturtle#68]
With #57, sprite forward movements optionally track concurrent angle changes, depending on a `track_angle` argument value.

Turtle forward movements should support that argument too.

**Comment by tmontes** [comment]
PS: Failed to set labels and milestone using the latest version of TenFourFox on PPC Mac OS X 10.5.8?. I know the tech is old, but this is a seemingly simple thing to handle, no GitHub? Maybe not... :-/

PPS: It kind of works at issue creation time, but does not after the fact.

**Comment by tmontes** [comment]
More PS: Just used iOS client to set labels and milestone. *sigh!*

**Comment by classilla** [comment]
> PS: Failed to set labels and milestone using the latest version of TenFourFox on PPC Mac OS X 10.5.8?. I know the tech is old, but this is a seemingly simple thing to handle, no GitHub? Maybe not... :-/
> 
> PPS: It kind of works at issue creation time, but does not after the fact.

TenFourFox maintainer driveby: it's because the underlying engine is essentially Fx45 with patches, and so far I've not been able to get `async` and `await` working which the new Github backend requires. As you've noticed, it _sort of_ works, but some things just don't.

**Comment by tmontes** [comment]
@classilla, thanks for your driveway and note. And, above all, thanks a lot for your work on TenFourFox. It is much appreciated. :-) Every now and then I like to go back to my oldish PPC PowerBook, like I have while experimenting with this project on older hardware, and being able to use a modern web browser for the occasional need is very useful.

Note that my frustration was directed at GitHub, not TenFourFox! Why on earth should setting a label not be compatible with older Javascript engines? (then again, I really don't know about the challenges of maintaining the GitHub UI codebase, so there might be good reasons... it's a pity, though)

**Comment by tmontes** [comment]
> @classilla, thanks for your drive-by and note. And, above all, thanks a lot for your work on TenFourFox. It is much appreciated. :-) Every now and then I like to go back to my oldish PPC PowerBook, like I have while experimenting with this project on older hardware, and being able to use a modern web browser for the occasional need is very useful.
> 
> Note that my frustration was directed at GitHub, not TenFourFox! Why on earth should setting a label not be compatible with older Javascript engines? (then again, I really don't know about the challenges of maintaining the GitHub UI codebase, so there might be good reasons... it's a pity, though)

**Comment by classilla** [comment]
Believe me, I totally understand!
